### ISSUE TITLE
backup a2hosting.com files and databases to GCP storage

### ISSUE THREAD

**Issue by ewsopp** [UsabilityDynamics/www.energync.com#1]
Store into existing bucket folder at https://console.cloud.google.com/storage/browser/storage-energync-com/a2hosting.com%20backup%202018-12/?project=energync-com-829472&organizationId=450511995436

**Comment by fqjony** [comment]
@ewsopp backup loaded to GCP. It is a 3 databases and WP codebase. Please let me know if I should work more on this.

**Comment by ewsopp** [comment]
Thanks
